zml/zml

README.md
=> docs: fix Mnist typo

docs/tutorials/write_first_model.md
There was a const/var bug in the code shown.
Also, after adhering code to roughly 80col limit, the code does not need to scroll horizontally anymore.
=> docs: first model: fix const vs. var and 80col limit

docs/howtos/howto_torch2zml.md, tools/zml_utils.py
**Changes**
- zml_utils: fix `AttributeError: type object 'ActivationCollector' has no attribute 'CollectionOver'`
- zml_utils: remove dead code and comments
- docs(howto_torch2zml): add explanation on why `output` variable can be `None`
=> zml_utils: fix CollectionOver scope

zml/tensor.zig
User should use either `chunkExact` or `chunkAllowTrailing` to clarify what they want.
previous `chunk` was crashing on `Tensor(.{.a=10}).chunk(.a, 3)` 
`chunkAllowTrailing` will return **4** tensors: `.{.a=3}, .{.a=3}, .{.a=3}, .{.a=1}`
=> remove bugged Tensor.chunk

zml/tensor.zig
note: `dynamicSlice1d()` has been completely removed because the `test dynamicSlice` has already very similar test.
=> zml: move tests next to the tested function

README.md, docs/howtos/huggingface_access_token.md, docs/huggingface-access-token.md, docs/tutorials/getting_started.md
Indicate that it's also the standard location used by the CLI, and add the environment variable, too.
=> workspace: be a little more precise regarding the huggingface token

examples/llama/llama.zig, examples/llama/main.zig
This PR introduces sharding attributes to Llama weights to take advantage of Tensor Parallelism
=> Llama weights sharding

examples/.nvim.lua
`zig_exe_path` needs to be set for the LSP to work properly
=> Fix LSP in Neovim

pjrt/pjrt.zig, zml/buffer.zig, zml/module.zig
Some runtimes do not implement `PJRT_Event`. For those, we must dispatch on our own thread pool for buffer copies and wait on events only if the runtime returns them.
If there are no events, assume all operations are synchronous.
=> zml,pjrt: account for runtimes that not implementing Events

zml/aio/safetensors.zig
For sharded safetensor files, we already have a separate json file we need to read.
Let's allow writing metadata there, to avoid having a separate json file with the model config.
=> zml/aio: allow metadata to be read from index.json

zml/aio.zig, zml/buffer.zig, zml/floats.zig, zml/helpers.zig, zml/nn.zig, zml/ops.zig, zml/tensor.zig
* add more scatterSlices testcases     
* zml: remove helpers.mapTensors in favor of zml.meta.map                   
* fix shape when for loop is fully unrolled                                 
* zml.Tensor.pad should accept i64 to be compatible with dims               
* allow to have array of tensor inside model struct
=> zml: small cleanup

bazel/zig.bzl, examples/llama/main.zig, examples/loader/main.zig, stdx/math.zig, zml/module.zig, zml/nn.zig
Due to miscommunication on my part, the tests were _not_ supposed to be failing!
=> zml: hotfixes for #89

runtimes/cuda/cuda.bzl, runtimes/cuda/libpjrt_cuda.BUILD.bazel
=> runtimes/cuda: fetch nccl from the pip package

async/BUILD.bazel, async/queue.zig, async/zigcoro.zig, stdx/signature.zig
all code contributed by @steeve
* add intrusive queue
* change the constructor of Channel with default AsyncThread executor
=> async: add intrusive queue

.gitignore, zml/context.zig, zml/exe.zig, zml/meta.zig, zml/testing.zig, zml/zml.zig
* testLayer was silently broken by #115 : test + fix so we detect this in the future. 
* mapAlloc had a regression in #115 wrt struct with 0 size fields: test + fix
* add Python `venv` to gitignore
=> Fix test layer

docs/tutorials/write_first_model.md
=> Tutorial updates for write_first_model.md

zml/module.zig
=> zml/module.zig: fix superfluous optional unwrapping

pjrt/convert/trace_container.zig, pjrt/convert/xplane_visitor.zig, pjrt/profiler.zig
* allow i64 resource id
* reserve memory when creating array lists
=> pjrt: Profiler fixes

examples/benchmark/main.zig, examples/llama/main.zig, examples/mnist/mnist.zig
Ooops! Forgot to update the examples.
=> examples: fix logFn usages

pjrt/profiler.zig
expose a more low-level function to customize where to write profile reports
=> pjrt: profiler support std writer API

zml/ops.zig
This can be used to select which branch will be run at runtime.
It wraps the `stablehlo.case` operation.
=> zml/ops.zig: Added `zml.ops.case` operation

mlir/dialects/BUILD.bazel, mlir/dialects/stablehlo.zig, zml/module.zig, zml/nn/cuda.zig, zml/ops.zig, zml/tensor.zig
=> mlir: rework stablehlo custom call

mlir/dialects/stablehlo.zig
Operand and result layouts are optionals cf [spec](https://github.com/openxla/xla/blob/7639178ebd11a1248a2fb3ac9138c1a14f0353aa/xla/mlir_hlo/mhlo/IR/hlo_ops.td#L2568-L2569)
=> stablehlo: fix custom call optional attributes forwarding

third_party/com_google_sentencepiece/repo.bzl, third_party/com_google_sentencepiece/sentencepiece.bazel
=> third_party/sentencepiece: add missing protobuf_lite dependency

.zed/settings.json
This PR adds Zed configuration.
=> workspace: add Zed settings

BUILD.bazel, examples/tools/zls.sh, third_party/zls/BUILD.bazel, tools/zls.sh
=> workspace: make zls runner target explicit

examples/.nvim.lua
=> workspace: updated default nvim configuration

examples/modernbert/modernbert.zig
I'm not sure about the default value. @vctrmn maybe you know better 😄
=> modernbert: set embeddings layernorm eps default value

runtimes/cpu/BUILD.bazel, runtimes/cpu/cpu.bzl, runtimes/cpu/cpu.zig
Same as TPU, simplified because there are no other NEEDED dependencies.
=> runtimes/cpu: sandbox CPU PJRT Plugin

MODULE.bazel, MODULE.bazel.lock, bazel/zig_proto_library.bzl, examples/MODULE.bazel.lock, third_party/com_google_sentencepiece/sentencepiece.bazel, upb/BUILD.bazel, upb/upb.zig, zml/BUILD.bazel, zml/module.zig
=> zml: remove zig-protobuf, switch to upb

README.md
This small PR fixes the `bazel.sh` source.
=> Update `bazel.sh` source
