README.md

Now that docs.zml.ai is up, users can decide to browse directly on GitHub or use the online documentation.

docs: add links to online docs to README

---

zml/tensor.zig

zml/tensor: fix typo in uniform comment

---

zml/test_runner.zig

**Motivation**
In some contexts we want to run only a subset of our test suite. 
This allow us to debug and trace more easily what's going on with failing tests.
Since we maintain our own test runner mainly to run in a async stack,
we can easily filter the list filled by `builtin.test_functions`
**Implementation**
I purpose a simple filtering without flags management, based on the first process argument.
- `bazel run -c opt //zml:test` will ran the full test suite as before this pull request.
- `bazel run -c opt //zml:test -- sdpa` or `bazel run -c opt //zml:test -- "sdpaMemEfficient without mask"` will run 
only tests with these words in the function name.
For later, it will gives us the opportunity to have a testing strategy.
Eg: `test "sdpaMemEfficient without mask - [tag1, tag2]" { …

zml/test_runner: add optional filtering on test functions list

---

zml/aio/torch.zig
zml/aio/torch/eval.zig
zml/aio/torch/parser.zig
zml/aio/torch/value.zig

Improve readability parsing pytorch model; optimize for reading slice w/o a single type as tuple.

aio: cleanup torch model parsing

---

mlir/dialects/stablehlo.zig
zml/aio.zig
zml/aio/yaml.zig
zml/buffer.zig
zml/hostbuffer.zig
zml/module.zig
zml/nn.zig
zml/shape.zig
zml/tensor.zig
zml/zml.zig

Add more `refAllDecl`
I had to fix resizeBilinear / resizeBicubic.
(85 tests now)
@cryptodeal  can you take over and fix nemo and yaml parsers ?

zml/nn: fix resize

---

zml/aio.zig
zml/aio/nemo.zig
zml/aio/torch.zig
zml/aio/torch/parser.zig
zml/aio/yaml.zig

Fix issues causing `std.testing.refAllDecls` to fail for `zml/aio/nemo.zig` and `zml/aio/yaml.zig`. Picks up where #18 left off.

aio: fix `refAllDecls` for `yaml`/`nemo`

---

MODULE.bazel
examples/MODULE.bazel.lock
runtimes/cpu/cpu.bzl
runtimes/cuda/cuda.bzl
runtimes/rocm/rocm.bzl
third_party/modules/llvm-raw/20240919.0-94c024a/MODULE.bazel
third_party/modules/llvm-raw/20240919.0-94c024a/overlay/MODULE.bazel
third_party/modules/llvm-raw/20240919.0-94c024a/overlay/utils/bazel/extension.bzl
third_party/modules/llvm-raw/20240919.0-94c024a/source.json
third_party/modules/llvm-raw/metadata.json
third_party/modules/stablehlo/20240917.0-78c753a/MODULE.bazel
third_party/modules/stablehlo/20240917.0-78c753a/overlay/MODULE.bazel
third_party/modules/stablehlo/20240917.0-78c753a/source.json
third_party/modules/stablehlo/metadata.json
third_party/modules/xla/20240919.0-1b18dd6/MODULE.bazel
third_party/modules/xla/20240919.0-1b18dd6/overlay/MODULE.bazel
third_party/modules/xla/20240919.0-1b18dd6/overlay/tsl.bzl
third_party/modules/xla/20240919.0-1b18dd6/overlay/workspace.bzl
third_party/modules/xla/20240919.0-1b18dd6/patches/0003-PJRT-C-API-Ensure-C-compliance-for-Profiler-Extensio.patch
third_party/modules/xla/20240919.0-1b18dd6/source.json
third_party/modules/xla/metadata.json
zml/tensor.zig

Since we were using an "old" version of XLA we where missing the batching dims stablehlo attribute.
This was preventing the usage of batching in the gather operator.
Since I had already wrote the batching test before hand and was just ignoring the compilation error,
this PR just bump xla and remove the error suppression code in tests.

workspace: bump xla to enabled batching in gather

---

zml/tensor.zig

When doing a `max` over a dimension, you have to start with the minimum value possible, otherwise you might miss the maximum.
Example:
Let's imagine you have a Tensor with the following values: `[-5, -4, -3, -2, -1]`
If you start with a value of `0`, the `max` in reduce will always return 0. Thus in the end, you get a maximum of `0` whereas `0` is not in the set of values.
Same for `min`

zml: Use correct init values for `Tensor.min()` and `Tensor.max()`

---

pjrt/pjrt.zig

On some platforms, the returned pointer is null so we can't use it as a slice, even if `num_dims` is 0.

PJRT: handle rank-0 special case in `getDimensions`

---

mlir/dialects/stablehlo.zig
mlir/mlir.zig

These functions can be used to serialize stablehlo in a portable way.

Add StableHLO bindings for functions related to versioning

---

examples/benchmark/main.zig
examples/simple_layer/main.zig
mlir/mlir.zig
pjrt/pjrt.zig
zml/aio.zig
zml/buffer.zig
zml/hostbuffer.zig
zml/meta.zig
zml/module.zig
zml/nn.zig
zml/pjrtx.zig
zml/platform.zig
zml/shape.zig
zml/tensor.zig

First rough support for in-process sharding.
The goal of sharding is to allow leveraging several GPUs to collaborate to run one big model.
Current implementation:
* added `platform.sharding()` describing how the set of devices managed by the current process should be used.
* added a `_sharding_info` to shape.
* A tensor / shape axis can be marked as needing sharding using `.withSharding(.{ .a })` or `.withSharding(.{ 1 })`.
* When using `populateModelWeights` tensors with sharded axes, will be populated by sharded buffers.
* when generating the MLIR bytecode for a ZML function the **input** arguments, will see their `_sharding_info` converted into `mhlo.sharding` attributes

zml: sharding

---

runtimes/rocm/packages.amd64.txt
runtimes/rocm/rocm.bzl

This PR updates the packages to the one at https://repo.radeon.com/rocm/apt/6.2.2/dists/focal/main/binary-amd64/Packages and bump and bump the ROCM_VERSION constant.
Tested on MI210 with Llama 3.1 8B Instruct.

runtimes/rocm: bump ROCm to 6.2.2

---

zml/BUILD.bazel

The end goal is to allow zml users to use our async test runner in their project.
This approach works but is a bit hacky because it relies on the fact that `test_runner.zig` is part of the `zml` library
otherwise `zig_test` doesn't correctly put the test_runner into the build sandbox.
I made this dependency explicit, but it was already the case because of the glob pattern used in zml library.
And I think `test_runner` should be `zig_library` in the first place, and not a filegroup.
See https://github.com/zml/rules_zig/issues/2 for follow up.

make `zml/test_runner.zig` public

---

examples/loader/main.zig
zml/aio/json.zig
zml/aio/safetensors.zig
zml/aio/torch.zig
zml/aio/torch/eval.zig
zml/aio/torch/ops.zig
zml/aio/torch/parser.zig
zml/aio/torch/value.zig

safetensor loader was segfaulting when loading metadata with an empty json array.
I also rewrote some of the torch loader code to improve the readability.
Notably every slice in `ops.zig` is now const. I've also realized that our strategy to load Pytorch tensor is not future proof see the warning at: https://pytorch.org/docs/stable/storage.html
we need to support the "UntypedStorage". @cryptodeal can you follow up on that ?

zml.aio.json: fix loading empty array

---

zml/aio/gguf.zig
zml/aio/sentencepiece.zig
zml/tokenizer.zig

We had issues with the CodeLlama tokenizer. https://huggingface.co/codellama/CodeLlama-7b-hf
Looking at the config, it's actually a "sentencepiece" tokenizer, that uses the special "▁" token to represent spaces.
```
"normalizer": {
"type": "Sequence",
"normalizers": [
{
"type": "Prepend",
"prepend": "▁"
},
{
"type": "Replace",
"pattern": {
"String": " "
},
"content": "▁"
}
]
},
```
I've added a `Normalizer.fromHfJson` that reads this json and tries to convert this style to our options.
This config can express more things than we can, so it's a best effort.
I've also made the magic space token configurable, requiring adding a small buffer in Normalizer to store it.
There is a small change that can have importance, is that now in most cases the setting "remove_extra_whitespaces" will not be …

Try to read normalizer setting from the huggingface json

---

zml/aio.zig
zml/module.zig
zml/testing.zig

`testLayer` was broken because it wasn't directly used by `llama.zig`.
Remove the uneeded "compile_options" argument,
update the testing logic to the new sharded output.

zml: fix `testLayer`

---

runtimes/cuda/cuda.bzl

This adds NCCL support which is required for proper sharding use

Bump PJRT CUDA Plugin to v0.2.3

---

zml/nn.zig
zml/tensor.zig

* add support for `Tensor.concatenate(&.{x, y}, .d)`
* start removing some `broadcastLeft` usage
* use f32 to compute head scaling constant in transformer. We should always compute constant with max precision.

zml: concatenate tag support

---

docs/howtos/dockerize_models.md

Added the missing import `zig_cc_binary` in the simple layer example, even though it seems obvious when you read the error

Add missing `load` in dockerize_models.md

---

zml/testing.zig

Handle all float types. Before we would crash if the reference tensor was in bfloat16.

zml/testing: handle all float types in tests

---

zml/tensor.zig

For `silu`, `logistic` is more precise than `sigmoid` since the first one is bound to StableHLO while the second one is a custom implementation. 
edit: after the discussion below I removed duplicated `logistic` operator to move the StableHLO call directly in `sigmoid`. The name is more "findable" than `logistic` and more aligned with what we have regarding activations functions; also if the user try to find `logistic` he will find it in the `sigmoid` implementation while the inverse is not true. I added a breaking change mention in the PR title too.

zml/tensor: use stablehlo.logistic for silu and remove logistic to implement it in sigmoid [BREAKING CHANGE]

---

async/async.zig
docs/tutorials/write_first_model.md
examples/benchmark/main.zig
examples/llama/main.zig
examples/loader/main.zig
examples/mnist/mnist.zig
examples/simple_layer/main.zig
zml/aio.zig
zml/module.zig

`asyncc` is arguably nicer to write than `async_`, so use that.
Also, add an explicit `Generic` version that can work with `anytype` functions (but on which type inference will be disabled).

async: rename async_ to asyncc and add Generic slugs

---

zml/context.zig
zml/posix.h

If we start bazel built binaries inside a ZML process, the environment has to be configured properly for the sub processes to find their runfiles properly.
Do it process wide at context start.

zml: configure runfiles env at context start

---

pjrt/BUILD.bazel
runtimes/BUILD.bazel
runtimes/cpu/BUILD.bazel
runtimes/cpu/cpu.zig
runtimes/cuda/BUILD.bazel
runtimes/cuda/cuda.zig
runtimes/rocm/BUILD.bazel
runtimes/rocm/rocm.zig
runtimes/rocm/zmlxrocm.cc
runtimes/runtimes.zig
runtimes/tpu/BUILD.bazel
runtimes/tpu/tpu.zig
zml/context.zig
zml/platform.zig

Add a tiny abstraction layer between ZML and PJRT.
Most notably, to implement custom logic to decide wether or not we should/can load a PJRT plugin.
For instance, `libtpu` will block the program trying to reach the GCP metadata server, which doesn't exist outside GCP.
This also allows for comptime detection of wether a runtime is linked with the program, and its dependencies.

runtimes: add intermediate abstraction layer

---

mlir/dialects/stablehlo.zig
zml/ops.zig
zml/shape.zig
zml/tensor.zig

This PR adds the "cumulative sum" operator.
This is based on what jax does, which is leveraging reduce window operator,
where for each n in [0..N] you compute the some of elements [0..n] 
I'm not sure how this get optimized in complex programs, to be investigated.
**BREAKING CHANGES**:
* `reduceWindow` is still pretty hard to used but I merged the `padding_shape` and `padding_value` into one operator and made the signature more explicit.
* this also lead me to change a bit how `maxPool1D` and `maxPool2D` take arguments, using proper tuples instead of slices that need to be of specific len.
* `pad` now take options using 
* "tagged syntax":`x.pad(0, .{ .a = .{ .low = 1, .high = -1 }});` 
* or the "AOS syntax":  `x.pad(0, &.{.{}, { .low = 1, .high = -1 }});`
* the "SOA syntax" is …

zml.tensor: add cumulativeSum, small refactor of maxPoolND

---

zml/nn.zig
zml/shape.zig
zml/tensor.zig
zml/testing.zig

- triangular: zeroes out the upper right part of a matrix. Options control how much is actually zeroes with offset from the diagonal.
- toDiagonal: equivalent to pytorch "diag_embed". The base case is converting a vector into a diagonal matrix. We already have a `diag` operator doing this, but the name was wrong cause in general `diag` does the reverse operation of extracting the diagonal from a matrix into a vector. Also it was using old style ZML, and was a bit too restrictive on input shapes.
- elu: one more activation function. it's getting a bit out of hand, I'm thinking about moving them out of Tensor namespace into zml.nn.Activation wdyt ?

zml.tensor: add triangular and toDiagonal

---

async/BUILD.bazel
async/meta.zig
async/threaded.zig
async/zigcoro.zig
zml/aio.zig
zml/module.zig

This implements the `async` module using a thread pool. This is now the default.
Implementations can be swapped using the `@zml//async:impl=[threaded,zigcoro]` flag.
Because io_uring is not enabled in the default seccomp profile, some container implementations will block on io_uring calls. Use the threaded implementation to work around this, for now.

async: add threaded implementation

---

mlir/mlir.zig
zml/pjrtx.zig
zml/tensor.zig

We currently have an issue with our version of openxla not being able to serialize the new "batching_dim" attribute of gather/scatter.
This is a version mismatch we should fix, but also it's bound to happen again, so since the compilation can fail, I'd rather return an error in that case.

pjrtx: error instead of panic

---

examples/benchmark/main.zig
examples/simple_layer/main.zig

Changes were made to `asynk` and not applied everywhere

examples: small cleanup

---

pjrt/pjrt.zig
zml/context.zig
zml/ops.zig
zml/tensor.zig

* restore the integration with PJRT custom call extension
* add a generic `zmlHostBufferCallback` custom call that copies the received tensor to the host, and call a user supplied callback on it.
* add a default "print" method on `Tensor` that print the runtime value of a given tensor
* print itself has very little code, it's easy for a user to define their own print if they don't like ours.
limitations:
* only supported on Cuda atm
* pre allocates a buffer on the host to copy the content of the device buffer,
this buffer won't be freed. There is exactly one buffer per "print" call in the IR.
* it uses cuda api, maybe I should be using `createViewOfDeviceBuffer` to make it less cuda specific

Add custom call support, and tensor.print()

---

mlir/dialects/stablehlo.zig
mlir/mlir.zig
zml/tensor.zig

It's midly annoying to have to specify iota dtype everywhere to .i32.
In practice if people want to work with floating point range of number they generally use arange.
Also `iota(x.shape(), 0).convert(.f32)` also work and isn't much work than saying `iota(x.shape(), .f32, 0)`
For good measure I've added a fallback to .i64 when the given axis has too many elements. I don't think this would cause much trouble, just because the tensor that big aren't very common in the first place.

zml: iota default to .i32

---

zml/nn.zig
zml/tensor.zig

Given the output of the last layer of a LM with a `.voc` axis,
Compute indices for the next tokens, following the given sampling strategy.
The dynamic sampling strategy is more expressive but top_p requires computing the softmax.
Options are:
* top_k: only sample among the k top scoring tokens,
* max_top_k: limit a compilation time what is the max possible runtime value for top_k, saving memory and compute by not having to fully sort the tokens.
* top_p: only sample among top scoring tokens whose probabilities sum up to top_p
* min_p: drop tokens whose probabilities are lower than a ratio of the most likely token

zml.nn: add dynamic sampling, supporting top-k, top-p, min-p settings

---

third_party/modules/zig-protobuf/20240722.0-c644d11/source.json

This was breaking old branches that didn't have these indentation changes

third_party/modules/zig-protobuf: revert indentation changes

---

zml/module.zig

Some PJRT executables get really large (e.g. ca. 300MB). We want to be able to load them.

Module-cache: increase max_pjrt_executable_size to 400MB

---

stdx/meta.zig
zml/aio.zig
zml/meta.zig
zml/shape.zig

fix a few `compileError` calls introduced by #89 . Zig compiler don't catch those until you trigger a comptime error.

fix a few compileError issues

---

stdx/meta.zig
zml/aio.zig
zml/meta.zig
zml/module.zig
zml/ops.zig
zml/shape.zig
zml/tensor.zig
zml/testing.zig

Now zml.ops.makeBlock returns both the mlir.Block created and also the Tensors returned by `func`.
The returned tensors should not be returned to the user,
because their `mlir.Value` must not escape the block that created them. But their shapes/tags can be safely propagated further.
This makes `zml.ops.makeBlock` a bit more footgunny, but also it's a utility function that most users shouldn't use. And it allows to use tags created inside the block and apply them to the return value. In particular tags and sharding info should now be propagated more consistently for while loops, summation, reduceWindow, ...
I've also enabled tests to run on non-cpu platform.
this is useful to figure out if a specific platform has limitation in it's pjrt support

zml: makeBlocks returns the inner tensor to propagate tags

---

examples/benchmark/main.zig
examples/simple_layer/main.zig

Recent changes to the `async` module reverted `asyncGeneric` to `asyncc` but examples were not updated

examples: fixes related to recent async changes

---

examples/.bazelrc
zml/module.zig
zml/nn.zig
zml/nn/cuda.zig
zml/tensor.zig
zml/testing.zig

Unroll the loop over key chunks manually in Zig.
We could use `zml.ops.while` but it's a bit verbose for when you just want to run a fixed number of steps.
`zml.ops.for_` was suppose to help with that,
but because it concatenates intermediary results, it wasn't saving memory.
Maybe we need to make `zml.ops.for` work similarly to `zml.ops.while` and add a `zml.ops.scan` for when we want to collect all intermediary results.
I hesitated to rewrite `sdpa` to call `sdpaChunk(q,k,v,opts).finalize()` but it doesn't work with `cuda.sdpa`

zml: fix memory usage of sdpaMemEfficient

---

zml/platform.zig

Some platform (such as Neuron) can have up to 32 devices, one per core.

zml/platform.zig: increase max device limit

---

zml/pjrtx.zig
zml/platform.zig

This was causing very bad performance for weight loading on Neuron because the calls are blocking

zml/pjrtx.zig: call `bufferFromHostBuffer` on the thread pool

---

pjrt/pjrt.zig
zml/context.zig

This allow us to find which NotFound is raised
-- 
~~require #106 to be merged before~~

workspace: log message before return NotFound 

---

mlir/dialects/stablehlo.zig
zml/pjrtx.zig

Discovered use case:
- PJRT plugin attribute `stablehlo_current_version` is `1.7.8`
- `stablehloVersionFromCompatibilityRequirement(WEEK_12)` is `1.1.0`
-  `stablehloGetCurrentVersion` is `1.7.6`
The target version for artifact serialization is `1.7.8` but should be `1.7.6`.
XLA ref: https://github.com/openxla/xla/commit/2f99455cdf99e844ddad17de9f4714997023d243#diff-7f335a78926dafcc06a6940ab5c1d5496f74a3431629e17e54df961e720e7574R213

zml/pjrtx: use framework's stablehlo version if plugin provided version is newer

---

examples/.bazelrc
zml/dtype.zig
zml/floats.zig
zml/mlir.zig
zml/nn.zig
zml/nn/cuda.zig
zml/tensor.zig

Mostly:
* fix float8 <-> float32 conversions
* support for `Tensor.constant(.{}, .{ .f8 = 1.0})` 
Misc:
* fix small inconsistencies between different versions of sdpa
* better error message for broadcast
* bazelrc: --config=debug

zml: fix float8 <-> float32 conversions, support for `Tensor.constant(.{}, .{ .f8 = 1.0})` 

---

examples/.bazelrc
examples/llama/llama.zig
zml/dtype.zig
zml/floats.zig
zml/mlir.zig
zml/module.zig
zml/nn.zig
zml/nn/cuda.zig
zml/tensor.zig

The current implementation first compute the full cos/sin matrix for the full sentence,
then slice into it to extract the positions for the current token.
This is generally optimized by the compiler so it's not a performance issue, but it's a readability issue,
because it means calling `rope` requires first a call to `ropeCosSin`.
I rewrote this to directly produce the optimized IR where we only compute rope for given offsets.

zml: revisit rope implementation

---

examples/llama/llama.zig
examples/llama/main.zig
zml/module.zig

Donate verything except the `token_index` buffer as it messes up the output

examples/llama+neuron: enable buffer donation

---

examples/benchmark/main.zig
examples/llama/main.zig
examples/mnist/mnist.zig
examples/simple_layer/main.zig
mlir/dialects/func.zig
stdx/meta.zig
stdx/signature.zig
zml/exe.zig
zml/meta.zig
zml/module.zig
zml/nn/cuda.zig
zml/testing.zig
zml/zml.zig

* compileInternal now works with function not with "module"
* BaseExe now allocates all the memory needed to call `pjrtExecute`
* `Exe` is the type variant of `BaseExe` and enforce the right Zig arg are passed to `call`. `exe.prepare(model)` don't need to allocate anymore, the allocation happened during compilation.
* public entry points like `compile`, `compileModel`, `compileFn` are now at the top of the file
* the caching logic has been mostly inlined inside `compileInternal`
* `compile`, `compileFn`, `Exe`, `BaseExe` which are the user visible API have been moved to `exe.zig`
* `CompilationContext` and all the compilation logic stays in `module.zig`

zml: cleanup module.zig

---

examples/llama/llama.zig
examples/llama/main.zig
mlir/dialects/func.zig
mlir/dialects/stablehlo.zig
mlir/mlir.zig
zml/meta.zig
zml/module.zig
zml/ops.zig
zml/testing.zig

Restore the machinery to emit individual functions and calls to them.
this should unblock composites, and generates cleaner MLIR in general
* functions are cached based on the input shapes including tags.
* donations/tags are propagated through function calls

zml: emit `func.call` operations

---

README.md
examples/MODULE.bazel
examples/llama/BUILD.bazel
examples/llama/llama.zig
examples/llama/main.zig

llama 3.2 1B and 3B do not have lm_head. 
I've added transposing over the embed_tokens as a replacement and set lm_head as optional for backward compatibility with the other models. 
I also added both repositories+executions to bazel and updated the README.

Llama 3.2 (text only models) support

---

.github/workflows/commit.yaml

Run `bazel build //llama` in CI to make sure we don't accidentally break it.
I'm also building all the examples target.
For reference it took 5 minutes to run this CI.

ci: build the examples directory

---

docs/howtos/howto_torch2zml.md
docs/tutorials/write_first_model.md
examples/benchmark/main.zig
examples/llama/main.zig
examples/llama/test.zig
examples/loader/main.zig
examples/mnist/mnist.zig
examples/simple_layer/main.zig
pjrt/pjrt.zig
zml/context.zig
zml/pjrtx.zig
zml/platform.zig
zml/testing.zig

The Pjrt api allows to passe string flags to the plugin on client creation.
Since we don't like working with strings I've converted the strings supported by the cuda plugin into a struct.
For now I've focused on the strings corresponding to the allocator settings following #125 let me know if you think 
that we should expose more from:
https://github.com/openxla/xla/blob/3d31c48c719d331d432132b3e0c2c5ce52650675/xla/pjrt/c/pjrt_c_api_gpu_internal.cc#L76-L86
AFAICT the cpu plugin doesn't read flags at all.
Will need some investigation for TPU and neuron platforms
**Breaking change**: `context.autoPlatform()` -> `context.autoPlatform(.{})`

pjrt/zml: expose client creation flags

---

stdx/meta.zig
stdx/signature.zig
zml/aio.zig
zml/module.zig
zml/nn.zig
zml/ops.zig
zml/tensor.zig
zml/testing.zig

* add an arena to the CompilationContext
There was already an allocator in the CompilationContext, this PR makes it into an arena and expose the arena allocator.
This allows ops that need to allocate to do so without abusing `std.BoundedArray` with arbitrary bounds, and in a safe way.
For now little ops use it, which I believe should stay the case, because most of the time you want to know how many tensor you're working with.
It'll also simplify the life of Zig new-comers
this include some **breaking changes** to `chunkAllowTrailing` and `split` that are allocating
* upgrade a few `axis_: i64` into `axis_: anytype` to handle tags
* add a few TODO for the next version of the Tensor API

zml: add an arena to the CompilationContext

---

examples/llama/main.zig
pjrt/BUILD.bazel
pjrt/convert/trace_container.zig
pjrt/pjrt.zig
pjrt/profiler.zig
runtimes/neuron/neuron.zig
stdx/meta.zig
zml/module.zig
zml/platform.zig
zml/testing.zig

* create one folder per target, then one sub-folder per mlir module.
* pass this folder to `xla_dump_to` so that all the xla files arrive there.
* explicitly save the mlir and the serialized executable there
I'm also exposing James profile conversion tool into ZML as `profiler.dumpDataAsJson(file)`

zml: Reorganize the compilation output folders

---

examples/llama/llama.zig
mlir/mlir.zig
pjrt/profiler.zig
zml/module.zig
zml/platform.zig
zml/shape.zig
zml/tensor.zig

Rewrite trivial transpose into reshapes.
Transpose over a 1-d axis are effectively no-op.
Normally the backend can detect this, but we observe that some backend can get confused. So avoiding those extra transpose can help.
I also changed the default profiler size to 1_000_000 events because above that the perfetto ui can't load the generated file anyway

zml: rewrite simple transpose

---

zml/hostbuffer.zig
zml/module.zig
zml/tensor.zig
zml/testing.zig

Add pretty printing of HostBuffer.
This will be leverage by the debug helper `x.print()`
It can also be used like this: `std.log.info("my buffer: {}", .{host_buffer.pretty()})`

zml: HostBuffer.prettyPrint()

---

examples/mnist/mnist.zig
zml/hostbuffer.zig
zml/module.zig
zml/nn.zig
zml/nn/cuda.zig
zml/shape.zig
zml/tensor.zig
zml/testing.zig
zml/zml.zig

Put the name of the operator in the source location.
This seemed redundant at first because it's not needed when looking at the stablehlo,
but it's nice to have it to understand the optimization passes.
I'm also including a few QoL:
* sdpa don't need a bias argument, attn_mask already play this role.
* gatherSlices should accept a shape literal `.{ .a = 5, .b = 128 }`
* Shape.outer to combine two shapes into the superset of their axes
* Tensor.all (since we already have Tensor.any)
* argMax doesn't need to specify the dtype, it can be inferred from the size of the input tensors. If the user care about the dtype they can manually convert.
This PR is stacked on top of #147

zml: improve source locations

---

zml/meta.zig
zml/module.zig
zml/ops.zig
zml/shape.zig
zml/tensor.zig
zml/torch.zig

Main issue with current `scatter` implementation is that it uses broadcasting dims of `stablehlo.scatter`.
While nice in theory, the optimizer doesn't handle them well and they often are unrolled into while loop.
Here I convert the batching dim to extra iotas indices.

zml: revamp scatterSlices

---

MODULE.bazel
async/async.zig
async/asyncio.zig
async/coro.zig
examples/MODULE.bazel
examples/llama/main.zig
runtimes/cpu/BUILD.bazel
runtimes/cpu/cpu.zig
runtimes/cuda/cuda.zig
runtimes/neuron/neuron.zig
runtimes/rocm/rocm.zig
runtimes/tpu/tpu.zig
third_party/modules/libxev/20241208.1-db6a52b/MODULE.bazel
third_party/modules/libxev/20241208.1-db6a52b/overlay/BUILD.bazel
third_party/modules/libxev/20241208.1-db6a52b/overlay/MODULE.bazel
third_party/modules/libxev/20241208.1-db6a52b/overlay/main2.zig
third_party/modules/libxev/20241208.1-db6a52b/patches/128.patch
third_party/modules/libxev/20241208.1-db6a52b/source.json
zml/aio.zig

Rework the libxev epoll backend to play nice with zigcoro based scheduler.
In the process, load the PJRT plugins using `callBlocking` because it can a bit slow sometimes.
Should have a slight performance increase, too.

async: fix async hangs

---

runtimes/rocm/libpjrt_rocm.BUILD.bazel
runtimes/rocm/rocm.bzl
runtimes/rocm/rocm.zig

Only the PJRT plugin needs hooking.
Make sure that hipblastlt bytecodes are optional, too.

runtimes/rocm: fix sandboxing and zmlxrocm hooks

---

examples/llama/BUILD.bazel
examples/llama/test_tokenizer.zig
zml/aio/tinyllama.zig
zml/hostbuffer.zig
zml/tokenizer.zig

Fix #134 , superseed #133
Basically the llama3 tokenizer.json has the following config: 
```
"model": {
"type": "BPE",
"dropout": null,
"unk_token": null,
"continuing_subword_prefix": null,
"end_of_word_suffix": null,
"fuse_unk": false,
"byte_fallback": false,
...
}
```
this it technically invalid because it says the model has no byte fallback and no unknown token either.
This means that unknown emoji can't be converted to bytes nor to the special unknown token.
This ended up in tokenizer.zig using the value of MAX_INT for the UNK token then panicking for out of bound.
So I've added some logic to recognize that in the case of GPT2 encoded vocab (like llama3) that actually contains individual bytes, we should use the "byte_fallback" algorithm even if disabled.
I've also added a Llama3 …

Llama3.2: fix tokenizer

---

runtimes/cuda/cuda.bzl
runtimes/cuda/cuda.zig
runtimes/cuda/libpjrt_cuda.BUILD.bazel
zml/module.zig

There is a performance regression on XLA master and 0.5.0.
Get back to 0.4.38 for now.

runtimes/cuda: downgrade the PJRT plugin back to 0.4.38

---

runtimes/cpu/cpu.bzl
runtimes/rocm/libpjrt_rocm.BUILD.bazel
runtimes/tpu/libpjrt_tpu.BUILD.bazel

Sometimes we require prebuilt PJRT plugins from outside (neuron, TPU...), and their `SONAME` are wrong.
Let's ensure all the plugins have their soname proper.

runtimes: properly set sonames

---

async/async.zig
async/executor.zig

Stop using a real mutex for the `logFn` and use an `Mutex` and allow for a fallback logger if outside a coroutine.

async: async mutex on log and fixes on ResetCondition

---

examples/llama/llama.zig
examples/llama/main.zig

This PR fixes issue #170 , making Llama run again on CUDA and RoCM.
- Latest Llama changes had introduced an unnecessary batching dimension: fixed
- Ops returning indices return i32 yet we now use u32 as token indices -> dtype conversion requred: fixed
Tested on CUDA.

llama: fix dims & dtypes -> fix #170

---

bazel/huggingface.bzl

If a file is in Git LFS, use the oid as the sha256 for the download.

bazel: fix random huggingface redownloads by using sha256

---

MODULE.bazel
examples/.bazelrc

This removes ~1300 build steps by depending on prebuilt binaries.
Note that this PR is blocked by https://github.com/aspect-build/toolchains_protoc/pull/44 since `rules_proto` depends on `protobuf@29.1` and https://github.com/aspect-build/toolchains_protoc doesn't expose `protoc@29.1` and we can't pin module versions unless adding an entry in the local BCR which I think is overkill for this.

bazel: use prebuilt protoc binaries

---

examples/llama/main.zig

There was an unnecessary re-encoding of the newline string, and we added a newline at the end.

llama: clean up llama3 prompt template encoding.

---

mlir/dialects/stablehlo.zig
pjrt/pjrt.zig
zml/buffer.zig
zml/pjrtx.zig

This preliminary PR binds PJRT memory endpoints and adds them to `zml.Buffer`.
A follow up PR will properly integrate it inside `zml.Buffer`

pjrt,zml: add memory bindings

---

async/async.zig

Since change allow use to leverage io_uring instead of xev if the backend is supported.

async: detect xev most preferable backend to use

---

third_party/zls/zls.bzl

Fix incorrect checksum for ZLS 0.14.0 x86_64-macos.tar.xz download

Fix zls_x86_64-macos incorrect checksum

---

async/async.zig

ref: https://github.com/mitchellh/libxev/blob/94ed6af7b2aaaeab987fbf87fcee410063df715b/src/dynamic.zig#L44

async: detect xev only if the API is dynamic (fix macOS)

---

examples/.vscode/settings.json

The extension checks that the ZLS path is absolute, else it will run which to find it in the PATH.
Add a heading / so that the path looks absolute. This works because we use ${workspaceFolder}.

workspace: fix vscode-zig update

---

async/coro.zig
async/executor.zig

currently using async.LogFn inside async runtime itself panics.
So I'm avoiding that by forcing async.zig logging to go through std.log.defaultLog which is synchronous.
you can reproduce the crash by changing log level to .debug

async should only use sync logging

---

zml/tensor.zig

The `_output_memory_kind` in the returned result was not set correctly

zml/tensor.zig: fix returned value in Tensor.toMemory

---

stdx/BUILD.bazel
stdx/fmt.zig
stdx/stdx.zig
zml/hostbuffer.zig

this is an improved version from what was implemented in "prettyPrinter" but I had to dig a bit into the fmt internal to achieve it.

stdx.fmt: format slices

---

runtimes/common/packages.bzl
runtimes/cuda/BUILD.bazel
runtimes/cuda/cuda.bzl
runtimes/cuda/libpjrt_cuda.h

This allows for custom calls to potentially use CUDA functions.

runtimes/cuda: add cuda.h to C namespace when using the CUDA runtimes

---

runtimes/common/packages.lock.json
runtimes/common/packages.yaml
runtimes/neuron/packages.lock.json
runtimes/neuron/packages.yaml

They are more reliable when pinning dependencies.
Replaces and Closes #111

runtimes: use cloudflare debian snapshots

---

zml/exe.zig
zml/meta.zig
zml/module.zig
zml/nn.zig
zml/ops.zig
zml/tensor.zig
zml/testing.zig
zml/torch.zig

this remove the need to pass `undefined` to `exe.call` when the corresponding `.forward` function expects integer/float arguments that have been inlined in the executable.
This was not needed and could just create confusion.
Now you may end up having to pass void to `exe.call` if the executable doesn't have any runtime argument,
but it's still better than passing `undefined`.
The only place that was using the non-buffer parts of a `zml.Bufferized` object was the infamous `zml.testing.compileAndCall`.
So I had to introduce a `zml.testing.BufferizedWithArgs` which is only used for this function.
I put it under the `zml.testing` namespace to make it clear it's only for this testing utility.
Note that because `compileAndCall` is strongly typed, you generally don't need to explicitly mention …

zml: remove compile time fields from zml.Bufferized

---

examples/benchmark/main.zig
examples/loader/main.zig
examples/mnist/mnist.zig
examples/simple_layer/main.zig
pjrt/pjrt.zig
zml/aio.zig
zml/buffer.zig
zml/hostbuffer.zig
zml/pjrtx.zig
zml/tensor.zig

* `Buffer.from` is blocking by default
* `Buffer.from` takes options to control the loading This includes awaiting for the buffer or to which memory the buffer is copied

zml/buffer: various improvements

---

examples/modernbert/modernbert.zig

Fixes compilation error in ModernBERT examples on my intel-based macbook pro.
ModernBERT failed to compile with sharding error:
```logs
info(modernbert): ✅	Loaded weights in 397ms
info(modernbert): 	Compiling ModernBERT model...
info(zml/exe): Compiling modernbert.ModernBertForMaskedLM.forward with { Shape({b=1,s=64,u32}) }
info(zml/module): Wrote MLIR to /private/tmp/zml/modernbert/cpu/modernbert.ModernBertForMaskedLM.forward_192023e1d2d0c331/module.mlir
2025-06-10 12:42:13.905711: I xla/service/dump.cc:562] HloModule dump enabled with path prefix: , suffix: before_optimizations
2025-06-10 12:42:13.981006: I xla/hlo/utils/hlo_sharding_util.cc:3079] There is no registered layout_canonicalization_callback.
WARNING: All log messages before absl::InitializeLog() is called are written to …
```

Fix ModernBERT compilation error by removing print calls

---

zml/aio.zig

Corrects the type annotation for init_args parameter to use the same 
conditional type as `loadBuffers` function. 
@Corendos

Patch aio.zig loadBuffersWithPrefix arguments

---

async/coro_base.zig

The first stack of each new coroutines were holding not zeroed and hold random memory data, which get popped in rbp during first coroutine stack swap.
Which made unwinding random or even SIGSEGV when _Unwind_Backtrace was used (during C++ exception for instance).
Zeroing the first part of the stack makes unwinding stop gracefully when it encounters $rbp=0x00.

async/coro: make coroutines unwindable
